### ISSUE TITLE
Accepteer mn pr ff Mirko op jou kan ik rekenen

### ISSUE THREAD

**Issue by jjvdt** [midje/.nl#4]
@mirkokroese @mirkokroese @mirkokroese 

Hier nog een foto van een paprika.
Dit is een normaal gesprek.

![image](https://user-images.githubusercontent.com/28925532/208243561-5111a6bb-2b25-43f2-a5ae-6e124e6ea186.png)

P.S.
@Justus1997 Hoeveel bench je nu eigenlijk?

**Comment by Justus1997** [comment]
Eerst de buggeltsies fixen heren!

**Comment by mirkokroese** [comment]
@Justus1997 Ik won't fix maatje

**Comment by mirkokroese** [comment]
@jjvdt jij mag wel fixen

**Comment by jjvdt** [comment]
Stek mar inne brân
